### PR TITLE
change command to lower case

### PR DESCRIPTION
**Pull request by lifengli**
to match its actual behavior

### CODE REVIEW

**Comment by jchip** [comment]
thank you. I prefer looking at the command keys in upper case. :) 
Isn't it better to make the input handler to convert `str` to lowercase so it's case insensitive?  
Note that `str` could be `undefined`.

**Comment by jchip** [comment]
@lifengli Hi, I want to check if you will be able to update this soon?

**Comment by lifengli** [comment]
> @lifengli Hi, I want to check if you will be able to update this soon?

Hi, please give me sometime since I'm new to this codebase. If you've already fixed it, feel free to publish it. Thanks,

**Comment by lifengli** [comment]
updated the PR, please review

**Pull request merged**
