### PR TITLE
electrode-archetype-react-app-dev: [patch][chore] Allow webpack config to override test entry point

### PR DESCRIPTION
**Pull request by Nickersona**
My goal here is to co-locate my test files with my components. Something I thought was possible with electrode but it must have changed at some point.  My solution is to make the test entry file overridable via the Webpack config. It's worked for my case, and gives me a ton of control over my testing environment which is very valuable to my project.  

Based on the naming of the webpack parital `test-entry.js` my assumption is that this was the intention of the webpack config file, but it doesn't look like it's being applied properly in the `karma.conf.js`.

Is there a reason that the test entry file is hard coded? This is quite limiting, but if there's an alternative way you'd suggest overriding the entry file I'd be interested to hear the approach.

### CODE REVIEW

**Comment by jchip** [comment]
Thanks for the PR.  Yes, the change makes sense.  Could you rebase to the latest please?

**Comment by Nickersona** [comment]
PR updated with the latest from master

**Comment by Nickersona** [comment]
@jchip Do you know why the tests would fail for this. I'm struggling to get them running locally on master. I'm not sure why they're failing

**Comment by jchip** [comment]
sorry, I will have to look into this later.

**Comment by jchip** [comment]
Hi, just looking this a bit.  Webpack config's entry points to the app's main JS file, usually `src/client/app.jsx`.  Also, it's not necessary a plain string.  It could be an object with multiple entry for webpack.  Karma's entry has to point to its own `entry.js`, which does bootstrapping to get the React app loaded into karma.  

I am not sure how this PR is supposed to work actually.

**Comment by Nickersona** [comment]
Thanks for looking into this. My approach was wrong here. I was able to accomplish what I wanted through a custom test Entry file. Closing the PR out.

**Pull request closed without merging**
