### PR TITLE
[patch] Fix above the fold path inside universal-react-node sample

### PR DESCRIPTION
**Pull request by didi0613**
skip true
skip true

skip false
skip false

### CODE REVIEW

**Comment by jchip** [comment]
please verify with `skip=true`?

**Comment by jchip** [comment]
Please show page source to verify that content below the fold are:

- Not rendered when skip=true
- Rendered when skip=false

**Comment by didi0613** [comment]
@jchip 
screen shot 2018-07-19 at 12 10 35 pm

**Comment by jchip** [comment]
`skip` is supposed to be passed in as `props`

**Comment by jchip** [comment]
The `skip` flag is only needed to be processed on the server side.

- remove `query-string` and do not do anything with it in the component.
- server side process the `skip` flag, set it in Redux initial state.
- pass the `skip` flag into the components through redux initial state

**Pull request merged**
