### PR TITLE
Default reporter socket port from env

### PR DESCRIPTION
**Pull request by codingcircus**
# Override standard reporter socket port

Since we are currently running multiple electrode apps in our dev environment, we run into a conflict, since the Webpack Reporter always uses the same standard port. This PR introduces a new environment variable called WEBPACK_REPORTER_SOCKET_PORT, that can be used to override the standard port 5000.

### CODE REVIEW

**Comment by jchip** [comment]
I prefer this to be passed in to webpack reporter from the archetype.  And have it processed here https://github.com/electrode-io/electrode/blob/master/packages/electrode-archetype-react-app-dev/config/archetype.js#L16, and pass to WebpackReporter here https://github.com/electrode-io/electrode/blob/master/packages/electrode-archetype-react-app-dev/config/webpack/partial/html-reporter.js#L8.

**Comment by codingcircus** [comment]
So if I understand correctly, we should just overwrite the default clap task `html-reporter`, is that right?

We already managed to do this, however, then I would at least propose, that you extend the current documentation, so that other developers find this information more quickly. 

Also my PR can be closed then.

**Comment by jchip** [comment]
I meant it's OK to have an env variable, but I want the archetype to process that env variable instead.

**Comment by codingcircus** [comment]
I updated my PR based on your last comments now

**Comment by jchip** [comment]
sorry, not sure what the CI failure was about, but merging it and will check.

**Pull request merged**
