### PR TITLE
Fix help message

### PR DESCRIPTION
**Pull request by dutradda**
Added the serverType option on help

### CODE REVIEW

**Comment by animesh10** [comment]
The prompt message is there already: https://github.com/electrode-io/electrode/blob/master/packages/generator-electrode/generators/app/index.js#L135-L140

**Comment by dutradda** [comment]
@animesh10 how to show the prompt? I ran the generator many times and this option just showed on versions prior 1.9..

**Comment by animesh10** [comment]
Yes, that was a bug that got introduced in that release. Thanks for noticing and raising the PR.
It has been fixed and will be available in the next release.

**Comment by animesh10** [comment]
Closing, since fix has been published.

**Pull request closed without merging**
