### PR TITLE
generator-electrode: [major] yeoman 1.1 and yarn support

### PR DESCRIPTION
**Pull request by donsalari**
Upgrade to yeoman v1.1  
Adding support for yarn install   
Upgrade dependencies

### CODE REVIEW

**Comment by thedrow** [comment]
This is why yarn doesn't work :man_facepalming: 
When will this land?

**Comment by donsalari** [comment]
@thedrow There is one minor issue I need to fix but I haven't got the time to do it recently. I'll take a look at it this week.

**Comment by donsalari** [comment]
All fixed. @animesh10 could you please test the latest?

**Comment by thedrow** [comment]
Is this merged or just not going to happen?

**Pull request closed without merging**
